name: Test and build

on: [pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

      - run: yarn install
      - run: yarn test
      - run: yarn run build
